version: '3'

services:
  nuxt-course-node:
    image: node:latest
    ports:
      - "3000:3000"
    volumes: 
      - ./app/:/usr/src/app:cached
    working_dir: '/usr/src/app'
    command: yarn dev -o
